/**
 * A util to detect if provided name is known (existing) oneicon name.
 *
 * @author Jakub Liput
 * @copyright (C) 2023 ACK CYFRONET AGH
 * @license This software is released under the MIT license cited in 'LICENSE.txt'.
 */

// FIXME: commented out for review - remove completely commented icons
export const knownOneicons = new Set([
  'add-filled',
  // 'add',
  'arrow-circle-down',
  'arrow-down',
  'arrow-left',
  // 'arrow-long-up',
  // 'arrow-right-full',
  'arrow-right',
  'arrow-up',
  'atm-inventory',
  'atm-lambda',
  'atm-workflow',
  'axes',
  // 'ban-left-thin',
  'ban-left',
  'browser-archive-add',
  'browser-archive-recall',
  'browser-archive-upload',
  'browser-archive',
  'browser-attribute',
  'browser-copy',
  'browser-cut',
  'browser-dataset-file',
  'browser-dataset',
  'browser-delete',
  'browser-directory',
  // 'browser-distribution',
  'browser-download',
  'browser-file',
  'browser-info',
  'browser-metadata',
  'browser-new-directory',
  'browser-paste',
  'browser-permission',
  'browser-permissions',
  'browser-rename',
  'browser-share',
  'browser-upload',
  'cancelled',
  'cart-checked',
  'cart',
  'certificate',
  'chart',
  // 'checkbox-check',
  // 'checkbox-empty',
  'checkbox-filled-warning',
  'checkbox-filled-x',
  'checkbox-filled',
  // 'checkbox-minus',
  // 'checkbox-option',
  'checkbox-pending',
  'checkbox-x',
  // 'checkbox',
  'checked',
  'circle-copy',
  'circle-id',
  'circle-not-available',
  'circle',
  'clean-filled',
  'clipboard-copy',
  'close',
  'cluster',
  // 'collection-create',
  'collection',
  'columns',
  'consume-token',
  // 'copy',
  'create-time',
  // 'cut',
  'data-receive',
  'data-send',
  // 'file',
  'flatten',
  // 'folder-new',
  // 'folder-open',
  // 'folder-share',
  // 'folder',
  'globe-cursor',
  'globe-filled',
  'globe',
  // 'group-add',
  'group-invite',
  'group-leave-group',
  'group',
  'groups',
  'hierarchy',
  // 'home-outline',
  'home',
  // 'inbox',
  'index',
  'info-modal',
  'inheritance',
  'invalidate',
  'items-grid',
  'join-plug',
  // 'join-space',
  // 'join',
  'key',
  'leave-space',
  'light-bulb',
  'link-external',
  'lock-checked',
  'lock',
  'logout',
  'markdown',
  // 'membership',
  // 'menu-clusters',
  // 'menu-collection',
  // 'menu-data',
  // 'menu-groups',
  // 'menu-providers',
  // 'menu-recent',
  // 'menu-shared',
  // 'menu-token',
  // 'menu-transfers',
  // 'menu-trash',
  // 'metadata',
  'move-down',
  'move-left',
  'move-right',
  'move-up',
  'move',
  'navigate-first',
  'navigate-last',
  'navigate-next',
  'navigate-prev',
  'no-view',
  'node',
  'onepanel',
  'onezone',
  'organization',
  'overview',
  // 'parents',
  // 'password-change',
  'pause',
  'permissions',
  'play',
  'plug-in',
  'plug-out',
  'plus',
  'properties',
  // 'provider-add',
  // 'provider-default',
  // 'provider-home',
  'provider',
  // 'providers-outline',
  'providers',
  'qos',
  'redo',
  'refresh',
  // 'remove',
  // 'rename',
  'rerun',
  'rest',
  'role-holders',
  'search',
  'settings-circle-filled',
  'settings',
  // 'share',
  // 'share-collection',
  'shortcut',
  'sign-error-rounded',
  // 'sign-error',
  'sign-info-rounded',
  // 'sign-info',
  'sign-question-rounded',
  // 'sign-question',
  'sign-warning-rounded',
  // 'sign-warning',
  'skipped',
  // 'social-dropbox',
  // 'social-egi',
  // 'social-facebook',
  // 'social-github',
  // 'social-google',
  // 'social-indigo',
  // 'social-plgrid',
  // 'social-rhea',
  'space-add',
  // 'space-default',
  'space-empty',
  // 'space-error',
  // 'space-home',
  // 'space-import-provider',
  'space-import',
  // 'space-join',
  // 'space-reload',
  'space',
  'square-empty',
  'square-minus-empty',
  'square-plus-empty',
  // 'star-empty',
  // 'star',
  'support',
  'team',
  'text-bold',
  'text-clear-formatting',
  'text-heading1',
  'text-heading2',
  'text-heading3',
  'text-italic',
  'text-link',
  'text-olist',
  'text-paragraph',
  'text-strikethrough',
  'text-ulist',
  'text-underline',
  'time',
  'token-access',
  'token-identity',
  'token-invite',
  'tokens',
  'transfers',
  'undo',
  'unit',
  'unknown',
  'update',
  // 'upload',
  // 'user-add',
  'user-profile',
  'user',
  'view-grid',
  'view-list',
  'view',
  'visual-editor',
  'warning',
  'x',
  'xml-file',
]);

export default function isOneicon(iconName) {
  return knownOneicons.has(iconName);
}
