export default [
  'name-conflict',
  'one-atlas',
  'one-dynamic-tree',
  'one-pie-chart',
  'one-tree',
  'one-way-toggle',
  'promise-proxy-container',
  'provider-place',
  'providers-list',
  'resource-load-error',
  'space-providers-support-chart',
  'status-toolbar',
  'support-size-info',
];
